server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mymiaosha?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: mymiaosha

  redis:
    host: 192.168.23.128
    timeout: 10000ms
    lettuce:
      pool:
        max-wait: 10000ms
        max-idle: 100

mybatis:
  mapper-locations: classpath:mapper/*

